sources/App.UI.Mvc5/Areas/Blank/Controllers/OverviewController.cs
using App.UI.Mvc5.Infrastructure;
using App.UI.Mvc5.Models;
using System.Web.Mvc;

namespace App.UI.Mvc5.Areas.Blank.Controllers
{
	[RoutePrefix("overview")]
	[TrackMenuItem("blank.overview")]
	public partial class OverviewController : __AreaBaseController
	{
		[Route(Name = "Blank_Overview_Index_Get")]
		public ActionResult Index()
		{
			var model = new EmptyViewModel();

			return View(model);
		}
	}
}

sources/App.UI.Mvc5/Areas/Blank/Controllers/_LandingController.cs
using System.Web.Mvc;

namespace App.UI.Mvc5.Areas.Blank.Controllers
{
	[RoutePrefix("")]
	public class _LandingController : __AreaBaseController
	{
		[HttpGet]
		[Route(Name = "Blank_Landing_Index_Get")]
		public ActionResult Index() => RedirectToAction("Index", "Overview");
	}
}

sources/App.UI.Mvc5/Areas/Blank/Controllers/_MenuController.cs
using App.UI.Mvc5.Models;
using System.Web.Mvc;

namespace App.UI.Mvc5.Areas.Blank.Controllers
{
	[RoutePrefix("menu")]
	public class _MenuController : __AreaBaseController
	{
		[Route("top-menu-item", Name = "Blank_Menu_TopMenuItem")]
		public ActionResult TopMenuItem()
		{
			var model = new EmptyPartialViewModel();

			return PartialView(model);
		}
	}
}

sources/App.UI.Mvc5/Areas/Blank/Controllers/__AreaBaseController.cs
using App.UI.Mvc5.Controllers;
using System.Web.Mvc;

namespace App.UI.Mvc5.Areas.Blank.Controllers
{
	[RouteArea("Blank", AreaPrefix = "blank")]
	public abstract class __AreaBaseController : __BaseController
	{
	}
}

sources/App.UI.Mvc5/Areas/Blank/Views/TopMenuItem.cshtml
@using App.UI.Mvc5.Areas.Blank

<!-- Page Contents -->

<li class="nav-item @Menu.IfActiveItem("blank.*", "active")">
	<a class="nav-link" href="@Url.Action("Index", "_Landing")">@(GetLocalizedString<AreaResources>("Blank"))</a>
</li>

sources/App.UI.Mvc5/Areas/Blank/Views/_LayoutArea.cshtml
@model BaseViewModel

<!-- Meta -->

@{
	this.SetLayout(Layouts.Internal);
}

<!-- Sections -->

@section page_styles {
	@RenderSection("page_styles", required: false)
}

@section page_scripts {
	@RenderSection("page_scripts", required: false)
}

@section page_scripts_init {
	@RenderSection("page_scripts_init", required: false)
}

<!-- Page Contents -->

@RenderBody()